AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
Description: >
  SQM Infrastracture - S3 Buckets - Nested Stack
  
Parameters:
  envName:
    Type: String
  
Conditions: 
  IsProd: 
    Fn::Equals:
      - !Ref envName
      - "prod"
  IsQA: 
    Fn::Equals:
      - !Ref envName
      - "qa"
  IsDev: 
    Fn::Equals:
      - !Ref envName
      - "dev"


        
Resources:

###########################################################################
###########             Frontend UI bucket                      ###########
###########################################################################
    frontendUIS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: !Sub "sqm-frontend-${AWS::AccountId}"
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          CorsConfiguration:
            CorsRules:
              - AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - GET
                AllowedOrigins:
                  - '*'
                ExposedHeaders: []
                MaxAge: 3600

###########################################################################
###########             Data Files Bucket                       ###########
###########################################################################
    DataFilesS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: !Sub "sqm-datafiles-${AWS::AccountId}"
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          CorsConfiguration:
            CorsRules:
              - AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - GET
                  - PUT
                  - POST
                  - DELETE
                AllowedOrigins:
                  - '*'
                ExposedHeaders: []
                MaxAge: 3600

Outputs:    
  DataFilesBucketName:
    Description: "Data Files S3 bucket"
    Value: !Ref DataFilesS3Bucket
    Export:
      Name: DataFilesBucketName
  WebAppBucketURL:
    Description: "Frontend UI S3 bucket"
    Value: !GetAtt frontendUIS3Bucket.WebsiteURL
    Export:
      Name: WebAppBucketURL
  WebAppBucketName:
    Description: "Frontend UI S3 bucket Name"
    Value: !Ref frontendUIS3Bucket
    Export:
      Name: WebAppBucketName
  WebAppBucketARN:
    Description: "ARN of the frontend UI S3 bucket"
    Value: !GetAtt frontendUIS3Bucket.Arn
    Export:
      Name: WebAppBucketARN