AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31
Description: 'SQM CloudFront Stack

  '
Parameters:
  envName:
    Type: String
  apiGatewayID:
    Type: String
  apiGatewayInvokeURL:
    Type: String
  webAppBucketURL:
    Type: String
  webAppBucketName:
    Type: String
  webAppBucketARN:
    Type: String
  certificateARN:
    Type: String
  apiCname:
    Type: String
  uiCname:
    Type: String
Resources:
  SQMCFResponseHeadersPolicies:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: SQMResponseHeadersPolicy
        Comment: SQM CloudFront Response Heafers Policy
        RemoveHeadersConfig:
          Items:
          - Header: X-Powered-By
        SecurityHeadersConfig:
          ContentSecurityPolicy:
            ContentSecurityPolicy: frame-ancestors 'self' *.towersemi.com
            Override: true
          ContentTypeOptions:
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: false
            Preload: false
        CorsConfig:
          OriginOverride: false
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
            - '*'
          AccessControlAllowMethods:
            Items:
            - ALL
          AccessControlAllowOrigins:
            Items:
            - '*.towersemi.com'
            - '*.towersemi.com:4200'
          AccessControlMaxAgeSec: 600
    Metadata:
      SamResourceId: SQMCFResponseHeadersPolicies
  AuthorizationCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Authorization Policy
        DefaultTTL: 0
        MaxTTL: 1
        MinTTL: 0
        Name: SQMAuthorizationPolicy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
            - Authorization
            - x-api-key
            - x-auth-token
    Metadata:
      SamResourceId: AuthorizationCachePolicy
  SQMAPICF:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - AuthorizationCachePolicy
    Properties:
      DistributionConfig:
        Comment: SQM API
        Aliases:
        - Ref: apiCname
        ViewerCertificate:
          AcmCertificateArn:
            Ref: certificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId:
            Fn::Join:
            - '-'
            - - sqm-api
              - Fn::Sub: ${AWS::AccountId}
          AllowedMethods:
          - GET
          - HEAD
          - POST
          - OPTIONS
          - PUT
          - PATCH
          - DELETE
          Compress: true
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId:
            Ref: AuthorizationCachePolicy
          ResponseHeadersPolicyId:
            Ref: SQMCFResponseHeadersPolicies
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
        - Id:
            Fn::Join:
            - '-'
            - - sqm-api
              - Fn::Sub: ${AWS::AccountId}
          DomainName:
            Fn::Sub: ${apiGatewayID}.execute-api.us-west-2.amazonaws.com
          OriginPath:
            Fn::Sub: /${envName}
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
            - TLSv1.2
        Restrictions:
          GeoRestriction:
            RestrictionType: blacklist
            Locations:
            - IR
            - IQ
            - SY
            - RU
            - BY
            - AF
            - KP
            - YE
    Metadata:
      SamResourceId: SQMAPICF
  SQMFrontendCF:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - AuthorizationCachePolicy
    - SQMFrontendBucketOAI
    Properties:
      DistributionConfig:
        Comment: SQM Frontend Web Application
        Aliases:
        - Ref: uiCname
        ViewerCertificate:
          AcmCertificateArn:
            Ref: certificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: SQMFrontend-Origin
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId:
            Ref: SQMCFResponseHeadersPolicies
        CacheBehaviors:
        - PathPattern: index.html
          TargetOriginId: SQMFrontend-Origin
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ResponseHeadersPolicyId:
            Ref: SQMCFResponseHeadersPolicies
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
        - Id: SQMFrontend-Origin
          DomainName:
            Ref: webAppBucketURL
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - ''
              - - origin-access-identity/cloudfront/
                - Ref: SQMFrontendBucketOAI
        CustomErrorResponses:
        - ErrorCachingMinTTL: 10
          ErrorCode: 400
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCachingMinTTL: 10
          ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCachingMinTTL: 10
          ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
        Restrictions:
          GeoRestriction:
            RestrictionType: blacklist
            Locations:
            - IR
            - IQ
            - SY
            - RU
            - BY
            - AF
            - KP
            - YE
    Metadata:
      SamResourceId: SQMFrontendCF
  SQMFrontendBucketOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: SQM Frontend CloudFrontOriginAccessIdentity
    Metadata:
      SamResourceId: SQMFrontendBucketOAI
  WebAppUIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
    - SQMFrontendBucketOAI
    Properties:
      Bucket:
        Ref: webAppBucketName
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - Ref: webAppBucketARN
              - /*
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - SQMFrontendBucketOAI
              - S3CanonicalUserId
    Metadata:
      SamResourceId: WebAppUIBucketPolicy
